services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn app:app -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/2
    volumes:
      - uploads:/app/tmp/uploads
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A celery_app.celery worker --loglevel=info
    env_file:
      - .env
    environment:
      - DB_HOST=host.docker.internal
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/2
    volumes:
      - uploads:/app/tmp/uploads
    depends_on:
      - redis
volumes:
  uploads: